[package]
name = "chess_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"
once_cell = "1.17.0"
egui = "0.21.0"
eframe = "0.21.3"
image = "0.24.5"
